### ISSUE TITLE
Retriever for some reason strips whitespace between {{variables}}

### ISSUE THREAD

**Issue by stereokai** [ysugimoto/Retriever#4]
FYI: http://jsperf.com/lodash-template/11

Retriever for some reason strips whitespace between `{{variables}}`.

**Comment by ysugimoto** [comment]
Hi stereokai.

Well, it had become the logic, such as to remove the white space in the control statement nested. 

https://github.com/ysugimoto/Retriever/blob/master/src/Parser.js#L206-L212 

According to the http://jsperf.com/lodash-template/11, 

```
<li>{{name}} is {{age}} years old. </ li>
```

compiles to

```
<li>{{name}}is{{age}}yearsold. </ li>
```

I'll Correct them, thank you!

**Comment by ysugimoto** [comment]
http://jsperf.com/lodash-template/11

Test passed.

**Comment by stereokai** [comment]
Outstanding! Glad that my test brought it to your attention. Retriever has great syntax, and is very straightforward.

However, your modification introduced a major hit in performance: before, I measured (multiple times), ~300k ops/sec on Chrome, and ~440k ops/sec on both Firefox and IE. Now however, _Chrome_ logs **~250k**, _Firefox_ is at a meager **~176k** – and on _IE_ Retriever still manages to deliver at **~336k** ops/sec.

Hopefully you can pinpoint what has brought your performance down.
